changes

diff --git a/.github/workflows/packer_status_check.yml b/.github/workflows/packer_status_check.yml
--- a/.github/workflows/packer_status_check.yml
+++ b/.github/workflows/packer_status_check.yml
@@ -18,11 +18,8 @@ jobs:
           sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
           sudo apt-get update && sudo apt-get install packer -y
 
-      - name: Set working directory
-        run: cd ./packer-template/
-
       - name: Run packer fmt
-        run: packer fmt -check ubuntu-mysql.pkr.hcl
+        run: packer fmt -check ./packer-template/ubuntu-mysql.pkr.hcl  # Updated path
 
       - name: Fail if packer fmt modifies the template
         run: |
@@ -40,15 +37,12 @@ jobs:
           sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
           sudo apt-get update && sudo apt-get install packer -y
 
-      - name: Set working directory
-        run: cd ./packer-template/
-
       - name: Initialize Packer
-        run: packer init ubuntu-mysql.pkr.hcl
+        run: packer init ./packer-template/ubuntu-mysql.pkr.hcl  # Updated path
 
       - name: Run packer validate
-        run: packer validate ubuntu-mysql.pkr.hcl
+        run: packer validate ./packer-template/ubuntu-mysql.pkr.hcl  # Updated path
 
       - name: Fail if packer validate fails
         run: |
-          packer validate ubuntu-mysql.pkr.hcl || (echo "Packer template validation failed!" && exit 1)
+          packer validate ./packer-template/ubuntu-mysql.pkr.hcl || (echo "Packer template validation failed!" && exit 1)
